name: base
pipelines:
  - render pass: gbuffer_pass
    rasterization:
      polygon mode: GERIUM_POLYGON_MODE_FILL
      cull mode: GERIUM_CULL_MODE_FRONT
      front face: GERIUM_FRONT_FACE_COUNTER_CLOCKWISE
      depth clamp enable: 0
      depth bias enable: 0
      depth bias constant factor: 0.0
      depth bias clamp: 0.0
      depth bias slope factor: 0.0
      line width: 1.0
    depth stencil:
      depth test enable: true
      depth write enable: true
      depth compare op: GERIUM_COMPARE_OP_GREATER_OR_EQUAL
    color blend:
      logic op enable: false
      logic op: GERIUM_LOGIC_OP_CLEAR
      blend constants: [0.0, 0.0, 0.0, 0.0]
    shaders:
      - type: GERIUM_SHADER_TYPE_TASK
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/gbuffer.task.glsl
      - type: GERIUM_SHADER_TYPE_MESH
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/gbuffer.mesh.glsl
      - type: GERIUM_SHADER_TYPE_FRAGMENT
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/gbuffer.frag.glsl
        
  - render pass: gbuffer_late_pass
    rasterization:
      polygon mode: GERIUM_POLYGON_MODE_FILL
      cull mode: GERIUM_CULL_MODE_FRONT
      front face: GERIUM_FRONT_FACE_COUNTER_CLOCKWISE
    depth stencil:
      depth test enable: true
      depth write enable: true
      depth compare op: GERIUM_COMPARE_OP_GREATER_OR_EQUAL
    shaders:
      - type: GERIUM_SHADER_TYPE_TASK
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/gbuffer.task.glsl
      - type: GERIUM_SHADER_TYPE_MESH
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/gbuffer.mesh.glsl
      - type: GERIUM_SHADER_TYPE_FRAGMENT
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/gbuffer.frag.glsl
        macros:
          - LATE: 1

  - render pass: present_pass
    shaders:
      - type: GERIUM_SHADER_TYPE_VERTEX
        lang: GERIUM_SHADER_LANGUAGE_HLSL
        name: shaders/screen.vert.hlsl
      - type: GERIUM_SHADER_TYPE_FRAGMENT
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/present.frag.glsl

  - render pass: culling_pass
    shaders:
      - type: GERIUM_SHADER_TYPE_COMPUTE
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/culling.comp.glsl

  - render pass: indirect_pass
    shaders:
      - type: GERIUM_SHADER_TYPE_COMPUTE
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/indirect.comp.glsl

  - render pass: indirect_late_pass
    shaders:
      - type: GERIUM_SHADER_TYPE_COMPUTE
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/indirect.comp.glsl

  - render pass: depth_pyramid_pass
    shaders:
      - type: GERIUM_SHADER_TYPE_COMPUTE
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/depth_reduce.comp.glsl
        macros:
          - INVERTED_Z: 1

  - render pass: culling_late_pass
    shaders:
      - type: GERIUM_SHADER_TYPE_COMPUTE
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/culling.comp.glsl
        macros:
          - LATE: 1
