#ifndef GERIUM_WINDOWS_VULKAN_UTILS_HPP
#define GERIUM_WINDOWS_VULKAN_UTILS_HPP

#include "../Gerium.hpp"
#include "../Handles.hpp"
#include "Enums.hpp"

namespace gerium::vulkan {

void check(VkResult result);

const VkAllocationCallbacks* getAllocCalls() noexcept;

gerium_inline bool hasDepthOrStencil(VkFormat format) noexcept {
    return format >= VK_FORMAT_D16_UNORM && format <= VK_FORMAT_D24_UNORM_S8_UINT;
}

gerium_inline bool hasStencil(VkFormat format) noexcept {
    return format >= VK_FORMAT_S8_UINT && format <= VK_FORMAT_D32_SFLOAT_S8_UINT;
}

gerium_inline bool hasDepth(VkFormat format) noexcept {
    return (format >= VK_FORMAT_D16_UNORM && format <= VK_FORMAT_D32_SFLOAT) ||
           (format >= VK_FORMAT_D16_UNORM_S8_UINT && format <= VK_FORMAT_D32_SFLOAT_S8_UINT);
}

gerium_inline VkFormat toVkFormat(gerium_format_t format) noexcept {
    switch (format) {
        case GERIUM_FORMAT_R4G4_UNORM:
            return VK_FORMAT_R4G4_UNORM_PACK8;
        case GERIUM_FORMAT_R4G4B4A4_UNORM:
            return VK_FORMAT_R4G4B4A4_UNORM_PACK16;
        case GERIUM_FORMAT_R5G5B5A1_UNORM:
            return VK_FORMAT_R5G5B5A1_UNORM_PACK16;
        case GERIUM_FORMAT_R5G6B5_UNORM:
            return VK_FORMAT_R5G6B5_UNORM_PACK16;
        case GERIUM_FORMAT_R8_UNORM:
            return VK_FORMAT_R8_UNORM;
        case GERIUM_FORMAT_R8_SNORM:
            return VK_FORMAT_R8_SNORM;
        case GERIUM_FORMAT_R8_UINT:
            return VK_FORMAT_R8_UINT;
        case GERIUM_FORMAT_R8_SINT:
            return VK_FORMAT_R8_SINT;
        case GERIUM_FORMAT_R8_SRGB:
            return VK_FORMAT_R8_SRGB;
        case GERIUM_FORMAT_R8_USCALED:
            return VK_FORMAT_R8_USCALED;
        case GERIUM_FORMAT_R8_SSCALED:
            return VK_FORMAT_R8_SSCALED;
        case GERIUM_FORMAT_R8G8_UNORM:
            return VK_FORMAT_R8G8_UNORM;
        case GERIUM_FORMAT_R8G8_SNORM:
            return VK_FORMAT_R8G8_SNORM;
        case GERIUM_FORMAT_R8G8_UINT:
            return VK_FORMAT_R8G8_UINT;
        case GERIUM_FORMAT_R8G8_SINT:
            return VK_FORMAT_R8G8_SINT;
        case GERIUM_FORMAT_R8G8_SRGB:
            return VK_FORMAT_R8G8_SRGB;
        case GERIUM_FORMAT_R8G8_USCALED:
            return VK_FORMAT_R8G8_USCALED;
        case GERIUM_FORMAT_R8G8_SSCALED:
            return VK_FORMAT_R8G8_SSCALED;
        case GERIUM_FORMAT_R8G8B8_UNORM:
            return VK_FORMAT_R8G8B8_UNORM;
        case GERIUM_FORMAT_R8G8B8_SNORM:
            return VK_FORMAT_R8G8B8_SNORM;
        case GERIUM_FORMAT_R8G8B8_UINT:
            return VK_FORMAT_R8G8B8_UINT;
        case GERIUM_FORMAT_R8G8B8_SINT:
            return VK_FORMAT_R8G8B8_SINT;
        case GERIUM_FORMAT_R8G8B8_SRGB:
            return VK_FORMAT_R8G8B8_SRGB;
        case GERIUM_FORMAT_R8G8B8_USCALED:
            return VK_FORMAT_R8G8B8_USCALED;
        case GERIUM_FORMAT_R8G8B8_SSCALED:
            return VK_FORMAT_R8G8B8_SSCALED;
        case GERIUM_FORMAT_R8G8B8A8_UNORM:
            return VK_FORMAT_R8G8B8A8_UNORM;
        case GERIUM_FORMAT_R8G8B8A8_SNORM:
            return VK_FORMAT_R8G8B8A8_SNORM;
        case GERIUM_FORMAT_R8G8B8A8_UINT:
            return VK_FORMAT_R8G8B8A8_UINT;
        case GERIUM_FORMAT_R8G8B8A8_SINT:
            return VK_FORMAT_R8G8B8A8_SINT;
        case GERIUM_FORMAT_R8G8B8A8_SRGB:
            return VK_FORMAT_R8G8B8A8_SRGB;
        case GERIUM_FORMAT_R8G8B8A8_USCALED:
            return VK_FORMAT_R8G8B8A8_USCALED;
        case GERIUM_FORMAT_R8G8B8A8_SSCALED:
            return VK_FORMAT_R8G8B8A8_SSCALED;
        case GERIUM_FORMAT_R16_UNORM:
            return VK_FORMAT_R16_UNORM;
        case GERIUM_FORMAT_R16_SNORM:
            return VK_FORMAT_R16_SNORM;
        case GERIUM_FORMAT_R16_UINT:
            return VK_FORMAT_R16_UINT;
        case GERIUM_FORMAT_R16_SINT:
            return VK_FORMAT_R16_SINT;
        case GERIUM_FORMAT_R16_SFLOAT:
            return VK_FORMAT_R16_SFLOAT;
        case GERIUM_FORMAT_R16_USCALED:
            return VK_FORMAT_R16_USCALED;
        case GERIUM_FORMAT_R16_SSCALED:
            return VK_FORMAT_R16_SSCALED;
        case GERIUM_FORMAT_R16G16_UNORM:
            return VK_FORMAT_R16G16_UNORM;
        case GERIUM_FORMAT_R16G16_SNORM:
            return VK_FORMAT_R16G16_SNORM;
        case GERIUM_FORMAT_R16G16_UINT:
            return VK_FORMAT_R16G16_UINT;
        case GERIUM_FORMAT_R16G16_SINT:
            return VK_FORMAT_R16G16_SINT;
        case GERIUM_FORMAT_R16G16_SFLOAT:
            return VK_FORMAT_R16G16_SFLOAT;
        case GERIUM_FORMAT_R16G16_USCALED:
            return VK_FORMAT_R16G16_USCALED;
        case GERIUM_FORMAT_R16G16_SSCALED:
            return VK_FORMAT_R16G16_SSCALED;
        case GERIUM_FORMAT_R16G16B16_UNORM:
            return VK_FORMAT_R16G16B16_UNORM;
        case GERIUM_FORMAT_R16G16B16_SNORM:
            return VK_FORMAT_R16G16B16_SNORM;
        case GERIUM_FORMAT_R16G16B16_UINT:
            return VK_FORMAT_R16G16B16_UINT;
        case GERIUM_FORMAT_R16G16B16_SINT:
            return VK_FORMAT_R16G16B16_SINT;
        case GERIUM_FORMAT_R16G16B16_SFLOAT:
            return VK_FORMAT_R16G16B16_SFLOAT;
        case GERIUM_FORMAT_R16G16B16_USCALED:
            return VK_FORMAT_R16G16B16_USCALED;
        case GERIUM_FORMAT_R16G16B16_SSCALED:
            return VK_FORMAT_R16G16B16_SSCALED;
        case GERIUM_FORMAT_R16G16B16A16_UNORM:
            return VK_FORMAT_R16G16B16A16_UNORM;
        case GERIUM_FORMAT_R16G16B16A16_SNORM:
            return VK_FORMAT_R16G16B16A16_SNORM;
        case GERIUM_FORMAT_R16G16B16A16_UINT:
            return VK_FORMAT_R16G16B16A16_UINT;
        case GERIUM_FORMAT_R16G16B16A16_SINT:
            return VK_FORMAT_R16G16B16A16_SINT;
        case GERIUM_FORMAT_R16G16B16A16_SFLOAT:
            return VK_FORMAT_R16G16B16A16_SFLOAT;
        case GERIUM_FORMAT_R16G16B16A16_USCALED:
            return VK_FORMAT_R16G16B16A16_USCALED;
        case GERIUM_FORMAT_R16G16B16A16_SSCALED:
            return VK_FORMAT_R16G16B16A16_SSCALED;
        case GERIUM_FORMAT_R32_UINT:
            return VK_FORMAT_R32_UINT;
        case GERIUM_FORMAT_R32_SINT:
            return VK_FORMAT_R32_SINT;
        case GERIUM_FORMAT_R32_SFLOAT:
            return VK_FORMAT_R32_SFLOAT;
        case GERIUM_FORMAT_R32G32_UINT:
            return VK_FORMAT_R32G32_UINT;
        case GERIUM_FORMAT_R32G32_SINT:
            return VK_FORMAT_R32G32_SINT;
        case GERIUM_FORMAT_R32G32_SFLOAT:
            return VK_FORMAT_R32G32_SFLOAT;
        case GERIUM_FORMAT_R32G32B32_UINT:
            return VK_FORMAT_R32G32B32_UINT;
        case GERIUM_FORMAT_R32G32B32_SINT:
            return VK_FORMAT_R32G32B32_SINT;
        case GERIUM_FORMAT_R32G32B32_SFLOAT:
            return VK_FORMAT_R32G32B32_SFLOAT;
        case GERIUM_FORMAT_R32G32B32A32_UINT:
            return VK_FORMAT_R32G32B32A32_UINT;
        case GERIUM_FORMAT_R32G32B32A32_SINT:
            return VK_FORMAT_R32G32B32A32_SINT;
        case GERIUM_FORMAT_R32G32B32A32_SFLOAT:
            return VK_FORMAT_R32G32B32A32_SFLOAT;
        case GERIUM_FORMAT_R64_UINT:
            return VK_FORMAT_R64_UINT;
        case GERIUM_FORMAT_R64_SINT:
            return VK_FORMAT_R64_SINT;
        case GERIUM_FORMAT_R64_SFLOAT:
            return VK_FORMAT_R64_SFLOAT;
        case GERIUM_FORMAT_R64G64_UINT:
            return VK_FORMAT_R64G64_UINT;
        case GERIUM_FORMAT_R64G64_SINT:
            return VK_FORMAT_R64G64_SINT;
        case GERIUM_FORMAT_R64G64_SFLOAT:
            return VK_FORMAT_R64G64_SFLOAT;
        case GERIUM_FORMAT_R64G64B64_UINT:
            return VK_FORMAT_R64G64B64_UINT;
        case GERIUM_FORMAT_R64G64B64_SINT:
            return VK_FORMAT_R64G64B64_SINT;
        case GERIUM_FORMAT_R64G64B64_SFLOAT:
            return VK_FORMAT_R64G64B64_SFLOAT;
        case GERIUM_FORMAT_R64G64B64A64_UINT:
            return VK_FORMAT_R64G64B64A64_UINT;
        case GERIUM_FORMAT_R64G64B64A64_SINT:
            return VK_FORMAT_R64G64B64A64_SINT;
        case GERIUM_FORMAT_R64G64B64A64_SFLOAT:
            return VK_FORMAT_R64G64B64A64_SFLOAT;
        case GERIUM_FORMAT_B4G4R4A4_UNORM:
            return VK_FORMAT_B4G4R4A4_UNORM_PACK16;
        case GERIUM_FORMAT_B5G5R5A1_UNORM:
            return VK_FORMAT_B5G5R5A1_UNORM_PACK16;
        case GERIUM_FORMAT_B5G6R5_UNORM:
            return VK_FORMAT_B5G6R5_UNORM_PACK16;
        case GERIUM_FORMAT_B8G8R8_UNORM:
            return VK_FORMAT_B8G8R8_UNORM;
        case GERIUM_FORMAT_B8G8R8_SNORM:
            return VK_FORMAT_B8G8R8_SNORM;
        case GERIUM_FORMAT_B8G8R8_UINT:
            return VK_FORMAT_B8G8R8_UINT;
        case GERIUM_FORMAT_B8G8R8_SINT:
            return VK_FORMAT_B8G8R8_SINT;
        case GERIUM_FORMAT_B8G8R8_SRGB:
            return VK_FORMAT_B8G8R8_SRGB;
        case GERIUM_FORMAT_B8G8R8_USCALED:
            return VK_FORMAT_B8G8R8_USCALED;
        case GERIUM_FORMAT_B8G8R8_SSCALED:
            return VK_FORMAT_B8G8R8_SSCALED;
        case GERIUM_FORMAT_B8G8R8A8_UNORM:
            return VK_FORMAT_B8G8R8A8_UNORM;
        case GERIUM_FORMAT_B8G8R8A8_SNORM:
            return VK_FORMAT_B8G8R8A8_SNORM;
        case GERIUM_FORMAT_B8G8R8A8_UINT:
            return VK_FORMAT_B8G8R8A8_UINT;
        case GERIUM_FORMAT_B8G8R8A8_SINT:
            return VK_FORMAT_B8G8R8A8_SINT;
        case GERIUM_FORMAT_B8G8R8A8_SRGB:
            return VK_FORMAT_B8G8R8A8_SRGB;
        case GERIUM_FORMAT_B8G8R8A8_USCALED:
            return VK_FORMAT_B8G8R8A8_USCALED;
        case GERIUM_FORMAT_B8G8R8A8_SSCALED:
            return VK_FORMAT_B8G8R8A8_SSCALED;
        case GERIUM_FORMAT_B10G11R11_UFLOAT:
            return VK_FORMAT_B10G11R11_UFLOAT_PACK32;
        case GERIUM_FORMAT_A1B5G5R5_UNORM:
            return VK_FORMAT_A1B5G5R5_UNORM_PACK16_KHR;
        case GERIUM_FORMAT_A1R5G5B5_UNORM:
            return VK_FORMAT_A1R5G5B5_UNORM_PACK16;
        case GERIUM_FORMAT_A2B10G10R10_UNORM:
            return VK_FORMAT_A2B10G10R10_UNORM_PACK32;
        case GERIUM_FORMAT_A2B10G10R10_SNORM:
            return VK_FORMAT_A2B10G10R10_SNORM_PACK32;
        case GERIUM_FORMAT_A2B10G10R10_UINT:
            return VK_FORMAT_A2B10G10R10_UINT_PACK32;
        case GERIUM_FORMAT_A2B10G10R10_SINT:
            return VK_FORMAT_A2B10G10R10_SINT_PACK32;
        case GERIUM_FORMAT_A2B10G10R10_USCALED:
            return VK_FORMAT_A2B10G10R10_USCALED_PACK32;
        case GERIUM_FORMAT_A2B10G10R10_SSCALED:
            return VK_FORMAT_A2B10G10R10_SSCALED_PACK32;
        case GERIUM_FORMAT_A2R10G10B10_UNORM:
            return VK_FORMAT_A2R10G10B10_UNORM_PACK32;
        case GERIUM_FORMAT_A2R10G10B10_SNORM:
            return VK_FORMAT_A2R10G10B10_SNORM_PACK32;
        case GERIUM_FORMAT_A2R10G10B10_UINT:
            return VK_FORMAT_A2R10G10B10_UINT_PACK32;
        case GERIUM_FORMAT_A2R10G10B10_SINT:
            return VK_FORMAT_A2R10G10B10_SINT_PACK32;
        case GERIUM_FORMAT_A2R10G10B10_USCALED:
            return VK_FORMAT_A2R10G10B10_USCALED_PACK32;
        case GERIUM_FORMAT_A2R10G10B10_SSCALED:
            return VK_FORMAT_A2R10G10B10_SSCALED_PACK32;
        case GERIUM_FORMAT_A4B4G4R4_UNORM:
            return VK_FORMAT_A4B4G4R4_UNORM_PACK16;
        case GERIUM_FORMAT_A4R4G4B4_UNORM:
            return VK_FORMAT_A4R4G4B4_UNORM_PACK16;
        case GERIUM_FORMAT_A8_UNORM:
            return VK_FORMAT_A8_UNORM_KHR;
        case GERIUM_FORMAT_A8B8G8R8_UNORM:
            return VK_FORMAT_A8B8G8R8_UNORM_PACK32;
        case GERIUM_FORMAT_A8B8G8R8_SNORM:
            return VK_FORMAT_A8B8G8R8_SNORM_PACK32;
        case GERIUM_FORMAT_A8B8G8R8_UINT:
            return VK_FORMAT_A8B8G8R8_UINT_PACK32;
        case GERIUM_FORMAT_A8B8G8R8_SINT:
            return VK_FORMAT_A8B8G8R8_SINT_PACK32;
        case GERIUM_FORMAT_A8B8G8R8_SRGB:
            return VK_FORMAT_A8B8G8R8_SRGB_PACK32;
        case GERIUM_FORMAT_A8B8G8R8_USCALED:
            return VK_FORMAT_A8B8G8R8_USCALED_PACK32;
        case GERIUM_FORMAT_A8B8G8R8_SSCALED:
            return VK_FORMAT_A8B8G8R8_SSCALED_PACK32;
        case GERIUM_FORMAT_S8_UINT:
            return VK_FORMAT_S8_UINT;
        case GERIUM_FORMAT_X8_D24_UNORM:
            return VK_FORMAT_X8_D24_UNORM_PACK32;
        case GERIUM_FORMAT_D16_UNORM:
            return VK_FORMAT_D16_UNORM;
        case GERIUM_FORMAT_D16_UNORM_S8_UINT:
            return VK_FORMAT_D16_UNORM_S8_UINT;
        case GERIUM_FORMAT_D24_UNORM_S8_UINT:
            return VK_FORMAT_D24_UNORM_S8_UINT;
        case GERIUM_FORMAT_D32_SFLOAT:
            return VK_FORMAT_D32_SFLOAT;
        case GERIUM_FORMAT_D32_SFLOAT_S8_UINT:
            return VK_FORMAT_D32_SFLOAT_S8_UINT;
        case GERIUM_FORMAT_ASTC_4x4_UNORM:
            return VK_FORMAT_ASTC_4x4_UNORM_BLOCK;
        case GERIUM_FORMAT_ASTC_4x4_SRGB:
            return VK_FORMAT_ASTC_4x4_SRGB_BLOCK;
        case GERIUM_FORMAT_ASTC_4x4_SFLOAT:
            return VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK;
        case GERIUM_FORMAT_ASTC_5x4_UNORM:
            return VK_FORMAT_ASTC_5x4_UNORM_BLOCK;
        case GERIUM_FORMAT_ASTC_5x4_SRGB:
            return VK_FORMAT_ASTC_5x4_SRGB_BLOCK;
        case GERIUM_FORMAT_ASTC_5x4_SFLOAT:
            return VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK;
        case GERIUM_FORMAT_ASTC_5x5_UNORM:
            return VK_FORMAT_ASTC_5x5_UNORM_BLOCK;
        case GERIUM_FORMAT_ASTC_5x5_SRGB:
            return VK_FORMAT_ASTC_5x5_SRGB_BLOCK;
        case GERIUM_FORMAT_ASTC_5x5_SFLOAT:
            return VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK;
        case GERIUM_FORMAT_ASTC_6x5_UNORM:
            return VK_FORMAT_ASTC_6x5_UNORM_BLOCK;
        case GERIUM_FORMAT_ASTC_6x5_SRGB:
            return VK_FORMAT_ASTC_6x5_SRGB_BLOCK;
        case GERIUM_FORMAT_ASTC_6x5_SFLOAT:
            return VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK;
        case GERIUM_FORMAT_ASTC_6x6_UNORM:
            return VK_FORMAT_ASTC_6x6_UNORM_BLOCK;
        case GERIUM_FORMAT_ASTC_6x6_SRGB:
            return VK_FORMAT_ASTC_6x6_SRGB_BLOCK;
        case GERIUM_FORMAT_ASTC_6x6_SFLOAT:
            return VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK;
        case GERIUM_FORMAT_ASTC_8x5_UNORM:
            return VK_FORMAT_ASTC_8x5_UNORM_BLOCK;
        case GERIUM_FORMAT_ASTC_8x5_SRGB:
            return VK_FORMAT_ASTC_8x5_SRGB_BLOCK;
        case GERIUM_FORMAT_ASTC_8x5_SFLOAT:
            return VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK;
        case GERIUM_FORMAT_ASTC_8x6_UNORM:
            return VK_FORMAT_ASTC_8x6_UNORM_BLOCK;
        case GERIUM_FORMAT_ASTC_8x6_SRGB:
            return VK_FORMAT_ASTC_8x6_SRGB_BLOCK;
        case GERIUM_FORMAT_ASTC_8x6_SFLOAT:
            return VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK;
        case GERIUM_FORMAT_ASTC_8x8_UNORM:
            return VK_FORMAT_ASTC_8x8_UNORM_BLOCK;
        case GERIUM_FORMAT_ASTC_8x8_SRGB:
            return VK_FORMAT_ASTC_8x8_SRGB_BLOCK;
        case GERIUM_FORMAT_ASTC_8x8_SFLOAT:
            return VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK;
        case GERIUM_FORMAT_ASTC_10x5_UNORM:
            return VK_FORMAT_ASTC_10x5_UNORM_BLOCK;
        case GERIUM_FORMAT_ASTC_10x5_SRGB:
            return VK_FORMAT_ASTC_10x5_SRGB_BLOCK;
        case GERIUM_FORMAT_ASTC_10x5_SFLOAT:
            return VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK;
        case GERIUM_FORMAT_ASTC_10x6_UNORM:
            return VK_FORMAT_ASTC_10x6_UNORM_BLOCK;
        case GERIUM_FORMAT_ASTC_10x6_SRGB:
            return VK_FORMAT_ASTC_10x6_SRGB_BLOCK;
        case GERIUM_FORMAT_ASTC_10x6_SFLOAT:
            return VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK;
        case GERIUM_FORMAT_ASTC_10x8_UNORM:
            return VK_FORMAT_ASTC_10x8_UNORM_BLOCK;
        case GERIUM_FORMAT_ASTC_10x8_SRGB:
            return VK_FORMAT_ASTC_10x8_SRGB_BLOCK;
        case GERIUM_FORMAT_ASTC_10x8_SFLOAT:
            return VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK;
        case GERIUM_FORMAT_ASTC_10x10_UNORM:
            return VK_FORMAT_ASTC_10x10_UNORM_BLOCK;
        case GERIUM_FORMAT_ASTC_10x10_SRGB:
            return VK_FORMAT_ASTC_10x10_SRGB_BLOCK;
        case GERIUM_FORMAT_ASTC_10x10_SFLOAT:
            return VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK;
        case GERIUM_FORMAT_ASTC_12x10_UNORM:
            return VK_FORMAT_ASTC_12x10_UNORM_BLOCK;
        case GERIUM_FORMAT_ASTC_12x10_SRGB:
            return VK_FORMAT_ASTC_12x10_SRGB_BLOCK;
        case GERIUM_FORMAT_ASTC_12x10_SFLOAT:
            return VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK;
        case GERIUM_FORMAT_ASTC_12x12_UNORM:
            return VK_FORMAT_ASTC_12x12_UNORM_BLOCK;
        case GERIUM_FORMAT_ASTC_12x12_SRGB:
            return VK_FORMAT_ASTC_12x12_SRGB_BLOCK;
        case GERIUM_FORMAT_ASTC_12x12_SFLOAT:
            return VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK;
        case GERIUM_FORMAT_BC1_RGB_UNORM:
            return VK_FORMAT_BC1_RGB_UNORM_BLOCK;
        case GERIUM_FORMAT_BC1_RGB_SRGB:
            return VK_FORMAT_BC1_RGB_SRGB_BLOCK;
        case GERIUM_FORMAT_BC1_RGBA_UNORM:
            return VK_FORMAT_BC1_RGBA_UNORM_BLOCK;
        case GERIUM_FORMAT_BC1_RGBA_SRGB:
            return VK_FORMAT_BC1_RGBA_SRGB_BLOCK;
        case GERIUM_FORMAT_BC2_UNORM:
            return VK_FORMAT_BC2_UNORM_BLOCK;
        case GERIUM_FORMAT_BC2_SRGB:
            return VK_FORMAT_BC2_SRGB_BLOCK;
        case GERIUM_FORMAT_BC3_UNORM:
            return VK_FORMAT_BC3_UNORM_BLOCK;
        case GERIUM_FORMAT_BC3_SRGB:
            return VK_FORMAT_BC3_SRGB_BLOCK;
        case GERIUM_FORMAT_BC4_UNORM:
            return VK_FORMAT_BC4_UNORM_BLOCK;
        case GERIUM_FORMAT_BC4_SNORM:
            return VK_FORMAT_BC4_SNORM_BLOCK;
        case GERIUM_FORMAT_BC5_UNORM:
            return VK_FORMAT_BC5_UNORM_BLOCK;
        case GERIUM_FORMAT_BC5_SNORM:
            return VK_FORMAT_BC5_SNORM_BLOCK;
        case GERIUM_FORMAT_BC6H_UFLOAT:
            return VK_FORMAT_BC6H_UFLOAT_BLOCK;
        case GERIUM_FORMAT_BC6H_SFLOAT:
            return VK_FORMAT_BC6H_SFLOAT_BLOCK;
        case GERIUM_FORMAT_BC7_UNORM:
            return VK_FORMAT_BC7_UNORM_BLOCK;
        case GERIUM_FORMAT_BC7_SRGB:
            return VK_FORMAT_BC7_SRGB_BLOCK;
        case GERIUM_FORMAT_ETC2_R8G8B8_UNORM:
            return VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK;
        case GERIUM_FORMAT_ETC2_R8G8B8_SRGB:
            return VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK;
        case GERIUM_FORMAT_ETC2_R8G8B8A1_UNORM:
            return VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK;
        case GERIUM_FORMAT_ETC2_R8G8B8A1_SRGB:
            return VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK;
        case GERIUM_FORMAT_ETC2_R8G8B8A8_UNORM:
            return VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK;
        case GERIUM_FORMAT_ETC2_R8G8B8A8_SRGB:
            return VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK;
        case GERIUM_FORMAT_EAC_R11_UNORM:
            return VK_FORMAT_EAC_R11_UNORM_BLOCK;
        case GERIUM_FORMAT_EAC_R11_SNORM:
            return VK_FORMAT_EAC_R11_SNORM_BLOCK;
        case GERIUM_FORMAT_EAC_R11G11_UNORM:
            return VK_FORMAT_EAC_R11G11_UNORM_BLOCK;
        case GERIUM_FORMAT_EAC_R11G11_SNORM:
            return VK_FORMAT_EAC_R11G11_SNORM_BLOCK;
        case GERIUM_FORMAT_PVRTC1_2BPP_UNORM:
            return VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG;
        case GERIUM_FORMAT_PVRTC1_2BPP_SRGB:
            return VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG;
        case GERIUM_FORMAT_PVRTC1_4BPP_UNORM:
            return VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG;
        case GERIUM_FORMAT_PVRTC1_4BPP_SRGB:
            return VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG;
        case GERIUM_FORMAT_PVRTC2_2BPP_UNORM:
            return VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG;
        case GERIUM_FORMAT_PVRTC2_2BPP_SRGB:
            return VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG;
        case GERIUM_FORMAT_PVRTC2_4BPP_UNORM:
            return VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG;
        case GERIUM_FORMAT_PVRTC2_4BPP_SRGB:
            return VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG;
        default:
            assert(!"unreachable code");
            return VK_FORMAT_UNDEFINED;
    }
}

gerium_inline gerium_format_t toGeriumFormat(VkFormat format) noexcept {
    switch (format) {
        case VK_FORMAT_R4G4_UNORM_PACK8:
            return GERIUM_FORMAT_R4G4_UNORM;
        case VK_FORMAT_R4G4B4A4_UNORM_PACK16:
            return GERIUM_FORMAT_R4G4B4A4_UNORM;
        case VK_FORMAT_R5G5B5A1_UNORM_PACK16:
            return GERIUM_FORMAT_R5G5B5A1_UNORM;
        case VK_FORMAT_R5G6B5_UNORM_PACK16:
            return GERIUM_FORMAT_R5G6B5_UNORM;
        case VK_FORMAT_R8_UNORM:
            return GERIUM_FORMAT_R8_UNORM;
        case VK_FORMAT_R8_SNORM:
            return GERIUM_FORMAT_R8_SNORM;
        case VK_FORMAT_R8_UINT:
            return GERIUM_FORMAT_R8_UINT;
        case VK_FORMAT_R8_SINT:
            return GERIUM_FORMAT_R8_SINT;
        case VK_FORMAT_R8_SRGB:
            return GERIUM_FORMAT_R8_SRGB;
        case VK_FORMAT_R8_USCALED:
            return GERIUM_FORMAT_R8_USCALED;
        case VK_FORMAT_R8_SSCALED:
            return GERIUM_FORMAT_R8_SSCALED;
        case VK_FORMAT_R8G8_UNORM:
            return GERIUM_FORMAT_R8G8_UNORM;
        case VK_FORMAT_R8G8_SNORM:
            return GERIUM_FORMAT_R8G8_SNORM;
        case VK_FORMAT_R8G8_UINT:
            return GERIUM_FORMAT_R8G8_UINT;
        case VK_FORMAT_R8G8_SINT:
            return GERIUM_FORMAT_R8G8_SINT;
        case VK_FORMAT_R8G8_SRGB:
            return GERIUM_FORMAT_R8G8_SRGB;
        case VK_FORMAT_R8G8_USCALED:
            return GERIUM_FORMAT_R8G8_USCALED;
        case VK_FORMAT_R8G8_SSCALED:
            return GERIUM_FORMAT_R8G8_SSCALED;
        case VK_FORMAT_R8G8B8_UNORM:
            return GERIUM_FORMAT_R8G8B8_UNORM;
        case VK_FORMAT_R8G8B8_SNORM:
            return GERIUM_FORMAT_R8G8B8_SNORM;
        case VK_FORMAT_R8G8B8_UINT:
            return GERIUM_FORMAT_R8G8B8_UINT;
        case VK_FORMAT_R8G8B8_SINT:
            return GERIUM_FORMAT_R8G8B8_SINT;
        case VK_FORMAT_R8G8B8_SRGB:
            return GERIUM_FORMAT_R8G8B8_SRGB;
        case VK_FORMAT_R8G8B8_USCALED:
            return GERIUM_FORMAT_R8G8B8_USCALED;
        case VK_FORMAT_R8G8B8_SSCALED:
            return GERIUM_FORMAT_R8G8B8_SSCALED;
        case VK_FORMAT_R8G8B8A8_UNORM:
            return GERIUM_FORMAT_R8G8B8A8_UNORM;
        case VK_FORMAT_R8G8B8A8_SNORM:
            return GERIUM_FORMAT_R8G8B8A8_SNORM;
        case VK_FORMAT_R8G8B8A8_UINT:
            return GERIUM_FORMAT_R8G8B8A8_UINT;
        case VK_FORMAT_R8G8B8A8_SINT:
            return GERIUM_FORMAT_R8G8B8A8_SINT;
        case VK_FORMAT_R8G8B8A8_SRGB:
            return GERIUM_FORMAT_R8G8B8A8_SRGB;
        case VK_FORMAT_R8G8B8A8_USCALED:
            return GERIUM_FORMAT_R8G8B8A8_USCALED;
        case VK_FORMAT_R8G8B8A8_SSCALED:
            return GERIUM_FORMAT_R8G8B8A8_SSCALED;
        case VK_FORMAT_R16_UNORM:
            return GERIUM_FORMAT_R16_UNORM;
        case VK_FORMAT_R16_SNORM:
            return GERIUM_FORMAT_R16_SNORM;
        case VK_FORMAT_R16_UINT:
            return GERIUM_FORMAT_R16_UINT;
        case VK_FORMAT_R16_SINT:
            return GERIUM_FORMAT_R16_SINT;
        case VK_FORMAT_R16_SFLOAT:
            return GERIUM_FORMAT_R16_SFLOAT;
        case VK_FORMAT_R16_USCALED:
            return GERIUM_FORMAT_R16_USCALED;
        case VK_FORMAT_R16_SSCALED:
            return GERIUM_FORMAT_R16_SSCALED;
        case VK_FORMAT_R16G16_UNORM:
            return GERIUM_FORMAT_R16G16_UNORM;
        case VK_FORMAT_R16G16_SNORM:
            return GERIUM_FORMAT_R16G16_SNORM;
        case VK_FORMAT_R16G16_UINT:
            return GERIUM_FORMAT_R16G16_UINT;
        case VK_FORMAT_R16G16_SINT:
            return GERIUM_FORMAT_R16G16_SINT;
        case VK_FORMAT_R16G16_SFLOAT:
            return GERIUM_FORMAT_R16G16_SFLOAT;
        case VK_FORMAT_R16G16_USCALED:
            return GERIUM_FORMAT_R16G16_USCALED;
        case VK_FORMAT_R16G16_SSCALED:
            return GERIUM_FORMAT_R16G16_SSCALED;
        case VK_FORMAT_R16G16B16_UNORM:
            return GERIUM_FORMAT_R16G16B16_UNORM;
        case VK_FORMAT_R16G16B16_SNORM:
            return GERIUM_FORMAT_R16G16B16_SNORM;
        case VK_FORMAT_R16G16B16_UINT:
            return GERIUM_FORMAT_R16G16B16_UINT;
        case VK_FORMAT_R16G16B16_SINT:
            return GERIUM_FORMAT_R16G16B16_SINT;
        case VK_FORMAT_R16G16B16_SFLOAT:
            return GERIUM_FORMAT_R16G16B16_SFLOAT;
        case VK_FORMAT_R16G16B16_USCALED:
            return GERIUM_FORMAT_R16G16B16_USCALED;
        case VK_FORMAT_R16G16B16_SSCALED:
            return GERIUM_FORMAT_R16G16B16_SSCALED;
        case VK_FORMAT_R16G16B16A16_UNORM:
            return GERIUM_FORMAT_R16G16B16A16_UNORM;
        case VK_FORMAT_R16G16B16A16_SNORM:
            return GERIUM_FORMAT_R16G16B16A16_SNORM;
        case VK_FORMAT_R16G16B16A16_UINT:
            return GERIUM_FORMAT_R16G16B16A16_UINT;
        case VK_FORMAT_R16G16B16A16_SINT:
            return GERIUM_FORMAT_R16G16B16A16_SINT;
        case VK_FORMAT_R16G16B16A16_SFLOAT:
            return GERIUM_FORMAT_R16G16B16A16_SFLOAT;
        case VK_FORMAT_R16G16B16A16_USCALED:
            return GERIUM_FORMAT_R16G16B16A16_USCALED;
        case VK_FORMAT_R16G16B16A16_SSCALED:
            return GERIUM_FORMAT_R16G16B16A16_SSCALED;
        case VK_FORMAT_R32_UINT:
            return GERIUM_FORMAT_R32_UINT;
        case VK_FORMAT_R32_SINT:
            return GERIUM_FORMAT_R32_SINT;
        case VK_FORMAT_R32_SFLOAT:
            return GERIUM_FORMAT_R32_SFLOAT;
        case VK_FORMAT_R32G32_UINT:
            return GERIUM_FORMAT_R32G32_UINT;
        case VK_FORMAT_R32G32_SINT:
            return GERIUM_FORMAT_R32G32_SINT;
        case VK_FORMAT_R32G32_SFLOAT:
            return GERIUM_FORMAT_R32G32_SFLOAT;
        case VK_FORMAT_R32G32B32_UINT:
            return GERIUM_FORMAT_R32G32B32_UINT;
        case VK_FORMAT_R32G32B32_SINT:
            return GERIUM_FORMAT_R32G32B32_SINT;
        case VK_FORMAT_R32G32B32_SFLOAT:
            return GERIUM_FORMAT_R32G32B32_SFLOAT;
        case VK_FORMAT_R32G32B32A32_UINT:
            return GERIUM_FORMAT_R32G32B32A32_UINT;
        case VK_FORMAT_R32G32B32A32_SINT:
            return GERIUM_FORMAT_R32G32B32A32_SINT;
        case VK_FORMAT_R32G32B32A32_SFLOAT:
            return GERIUM_FORMAT_R32G32B32A32_SFLOAT;
        case VK_FORMAT_R64_UINT:
            return GERIUM_FORMAT_R64_UINT;
        case VK_FORMAT_R64_SINT:
            return GERIUM_FORMAT_R64_SINT;
        case VK_FORMAT_R64_SFLOAT:
            return GERIUM_FORMAT_R64_SFLOAT;
        case VK_FORMAT_R64G64_UINT:
            return GERIUM_FORMAT_R64G64_UINT;
        case VK_FORMAT_R64G64_SINT:
            return GERIUM_FORMAT_R64G64_SINT;
        case VK_FORMAT_R64G64_SFLOAT:
            return GERIUM_FORMAT_R64G64_SFLOAT;
        case VK_FORMAT_R64G64B64_UINT:
            return GERIUM_FORMAT_R64G64B64_UINT;
        case VK_FORMAT_R64G64B64_SINT:
            return GERIUM_FORMAT_R64G64B64_SINT;
        case VK_FORMAT_R64G64B64_SFLOAT:
            return GERIUM_FORMAT_R64G64B64_SFLOAT;
        case VK_FORMAT_R64G64B64A64_UINT:
            return GERIUM_FORMAT_R64G64B64A64_UINT;
        case VK_FORMAT_R64G64B64A64_SINT:
            return GERIUM_FORMAT_R64G64B64A64_SINT;
        case VK_FORMAT_R64G64B64A64_SFLOAT:
            return GERIUM_FORMAT_R64G64B64A64_SFLOAT;
        case VK_FORMAT_B4G4R4A4_UNORM_PACK16:
            return GERIUM_FORMAT_B4G4R4A4_UNORM;
        case VK_FORMAT_B5G5R5A1_UNORM_PACK16:
            return GERIUM_FORMAT_B5G5R5A1_UNORM;
        case VK_FORMAT_B5G6R5_UNORM_PACK16:
            return GERIUM_FORMAT_B5G6R5_UNORM;
        case VK_FORMAT_B8G8R8_UNORM:
            return GERIUM_FORMAT_B8G8R8_UNORM;
        case VK_FORMAT_B8G8R8_SNORM:
            return GERIUM_FORMAT_B8G8R8_SNORM;
        case VK_FORMAT_B8G8R8_UINT:
            return GERIUM_FORMAT_B8G8R8_UINT;
        case VK_FORMAT_B8G8R8_SINT:
            return GERIUM_FORMAT_B8G8R8_SINT;
        case VK_FORMAT_B8G8R8_SRGB:
            return GERIUM_FORMAT_B8G8R8_SRGB;
        case VK_FORMAT_B8G8R8_USCALED:
            return GERIUM_FORMAT_B8G8R8_USCALED;
        case VK_FORMAT_B8G8R8_SSCALED:
            return GERIUM_FORMAT_B8G8R8_SSCALED;
        case VK_FORMAT_B8G8R8A8_UNORM:
            return GERIUM_FORMAT_B8G8R8A8_UNORM;
        case VK_FORMAT_B8G8R8A8_SNORM:
            return GERIUM_FORMAT_B8G8R8A8_SNORM;
        case VK_FORMAT_B8G8R8A8_UINT:
            return GERIUM_FORMAT_B8G8R8A8_UINT;
        case VK_FORMAT_B8G8R8A8_SINT:
            return GERIUM_FORMAT_B8G8R8A8_SINT;
        case VK_FORMAT_B8G8R8A8_SRGB:
            return GERIUM_FORMAT_B8G8R8A8_SRGB;
        case VK_FORMAT_B8G8R8A8_USCALED:
            return GERIUM_FORMAT_B8G8R8A8_USCALED;
        case VK_FORMAT_B8G8R8A8_SSCALED:
            return GERIUM_FORMAT_B8G8R8A8_SSCALED;
        case VK_FORMAT_B10G11R11_UFLOAT_PACK32:
            return GERIUM_FORMAT_B10G11R11_UFLOAT;
        case VK_FORMAT_A1B5G5R5_UNORM_PACK16_KHR:
            return GERIUM_FORMAT_A1B5G5R5_UNORM;
        case VK_FORMAT_A1R5G5B5_UNORM_PACK16:
            return GERIUM_FORMAT_A1R5G5B5_UNORM;
        case VK_FORMAT_A2B10G10R10_UNORM_PACK32:
            return GERIUM_FORMAT_A2B10G10R10_UNORM;
        case VK_FORMAT_A2B10G10R10_SNORM_PACK32:
            return GERIUM_FORMAT_A2B10G10R10_SNORM;
        case VK_FORMAT_A2B10G10R10_UINT_PACK32:
            return GERIUM_FORMAT_A2B10G10R10_UINT;
        case VK_FORMAT_A2B10G10R10_SINT_PACK32:
            return GERIUM_FORMAT_A2B10G10R10_SINT;
        case VK_FORMAT_A2B10G10R10_USCALED_PACK32:
            return GERIUM_FORMAT_A2B10G10R10_USCALED;
        case VK_FORMAT_A2B10G10R10_SSCALED_PACK32:
            return GERIUM_FORMAT_A2B10G10R10_SSCALED;
        case VK_FORMAT_A2R10G10B10_UNORM_PACK32:
            return GERIUM_FORMAT_A2R10G10B10_UNORM;
        case VK_FORMAT_A2R10G10B10_SNORM_PACK32:
            return GERIUM_FORMAT_A2R10G10B10_SNORM;
        case VK_FORMAT_A2R10G10B10_UINT_PACK32:
            return GERIUM_FORMAT_A2R10G10B10_UINT;
        case VK_FORMAT_A2R10G10B10_SINT_PACK32:
            return GERIUM_FORMAT_A2R10G10B10_SINT;
        case VK_FORMAT_A2R10G10B10_USCALED_PACK32:
            return GERIUM_FORMAT_A2R10G10B10_USCALED;
        case VK_FORMAT_A2R10G10B10_SSCALED_PACK32:
            return GERIUM_FORMAT_A2R10G10B10_SSCALED;
        case VK_FORMAT_A4B4G4R4_UNORM_PACK16:
            return GERIUM_FORMAT_A4B4G4R4_UNORM;
        case VK_FORMAT_A4R4G4B4_UNORM_PACK16:
            return GERIUM_FORMAT_A4R4G4B4_UNORM;
        case VK_FORMAT_A8_UNORM_KHR:
            return GERIUM_FORMAT_A8_UNORM;
        case VK_FORMAT_A8B8G8R8_UNORM_PACK32:
            return GERIUM_FORMAT_A8B8G8R8_UNORM;
        case VK_FORMAT_A8B8G8R8_SNORM_PACK32:
            return GERIUM_FORMAT_A8B8G8R8_SNORM;
        case VK_FORMAT_A8B8G8R8_UINT_PACK32:
            return GERIUM_FORMAT_A8B8G8R8_UINT;
        case VK_FORMAT_A8B8G8R8_SINT_PACK32:
            return GERIUM_FORMAT_A8B8G8R8_SINT;
        case VK_FORMAT_A8B8G8R8_SRGB_PACK32:
            return GERIUM_FORMAT_A8B8G8R8_SRGB;
        case VK_FORMAT_A8B8G8R8_USCALED_PACK32:
            return GERIUM_FORMAT_A8B8G8R8_USCALED;
        case VK_FORMAT_A8B8G8R8_SSCALED_PACK32:
            return GERIUM_FORMAT_A8B8G8R8_SSCALED;
        case VK_FORMAT_S8_UINT:
            return GERIUM_FORMAT_S8_UINT;
        case VK_FORMAT_X8_D24_UNORM_PACK32:
            return GERIUM_FORMAT_X8_D24_UNORM;
        case VK_FORMAT_D16_UNORM:
            return GERIUM_FORMAT_D16_UNORM;
        case VK_FORMAT_D16_UNORM_S8_UINT:
            return GERIUM_FORMAT_D16_UNORM_S8_UINT;
        case VK_FORMAT_D24_UNORM_S8_UINT:
            return GERIUM_FORMAT_D24_UNORM_S8_UINT;
        case VK_FORMAT_D32_SFLOAT:
            return GERIUM_FORMAT_D32_SFLOAT;
        case VK_FORMAT_D32_SFLOAT_S8_UINT:
            return GERIUM_FORMAT_D32_SFLOAT_S8_UINT;
        case VK_FORMAT_ASTC_4x4_UNORM_BLOCK:
            return GERIUM_FORMAT_ASTC_4x4_UNORM;
        case VK_FORMAT_ASTC_4x4_SRGB_BLOCK:
            return GERIUM_FORMAT_ASTC_4x4_SRGB;
        case VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK:
            return GERIUM_FORMAT_ASTC_4x4_SFLOAT;
        case VK_FORMAT_ASTC_5x4_UNORM_BLOCK:
            return GERIUM_FORMAT_ASTC_5x4_UNORM;
        case VK_FORMAT_ASTC_5x4_SRGB_BLOCK:
            return GERIUM_FORMAT_ASTC_5x4_SRGB;
        case VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK:
            return GERIUM_FORMAT_ASTC_5x4_SFLOAT;
        case VK_FORMAT_ASTC_5x5_UNORM_BLOCK:
            return GERIUM_FORMAT_ASTC_5x5_UNORM;
        case VK_FORMAT_ASTC_5x5_SRGB_BLOCK:
            return GERIUM_FORMAT_ASTC_5x5_SRGB;
        case VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK:
            return GERIUM_FORMAT_ASTC_5x5_SFLOAT;
        case VK_FORMAT_ASTC_6x5_UNORM_BLOCK:
            return GERIUM_FORMAT_ASTC_6x5_UNORM;
        case VK_FORMAT_ASTC_6x5_SRGB_BLOCK:
            return GERIUM_FORMAT_ASTC_6x5_SRGB;
        case VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK:
            return GERIUM_FORMAT_ASTC_6x5_SFLOAT;
        case VK_FORMAT_ASTC_6x6_UNORM_BLOCK:
            return GERIUM_FORMAT_ASTC_6x6_UNORM;
        case VK_FORMAT_ASTC_6x6_SRGB_BLOCK:
            return GERIUM_FORMAT_ASTC_6x6_SRGB;
        case VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK:
            return GERIUM_FORMAT_ASTC_6x6_SFLOAT;
        case VK_FORMAT_ASTC_8x5_UNORM_BLOCK:
            return GERIUM_FORMAT_ASTC_8x5_UNORM;
        case VK_FORMAT_ASTC_8x5_SRGB_BLOCK:
            return GERIUM_FORMAT_ASTC_8x5_SRGB;
        case VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK:
            return GERIUM_FORMAT_ASTC_8x5_SFLOAT;
        case VK_FORMAT_ASTC_8x6_UNORM_BLOCK:
            return GERIUM_FORMAT_ASTC_8x6_UNORM;
        case VK_FORMAT_ASTC_8x6_SRGB_BLOCK:
            return GERIUM_FORMAT_ASTC_8x6_SRGB;
        case VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK:
            return GERIUM_FORMAT_ASTC_8x6_SFLOAT;
        case VK_FORMAT_ASTC_8x8_UNORM_BLOCK:
            return GERIUM_FORMAT_ASTC_8x8_UNORM;
        case VK_FORMAT_ASTC_8x8_SRGB_BLOCK:
            return GERIUM_FORMAT_ASTC_8x8_SRGB;
        case VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK:
            return GERIUM_FORMAT_ASTC_8x8_SFLOAT;
        case VK_FORMAT_ASTC_10x5_UNORM_BLOCK:
            return GERIUM_FORMAT_ASTC_10x5_UNORM;
        case VK_FORMAT_ASTC_10x5_SRGB_BLOCK:
            return GERIUM_FORMAT_ASTC_10x5_SRGB;
        case VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK:
            return GERIUM_FORMAT_ASTC_10x5_SFLOAT;
        case VK_FORMAT_ASTC_10x6_UNORM_BLOCK:
            return GERIUM_FORMAT_ASTC_10x6_UNORM;
        case VK_FORMAT_ASTC_10x6_SRGB_BLOCK:
            return GERIUM_FORMAT_ASTC_10x6_SRGB;
        case VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK:
            return GERIUM_FORMAT_ASTC_10x6_SFLOAT;
        case VK_FORMAT_ASTC_10x8_UNORM_BLOCK:
            return GERIUM_FORMAT_ASTC_10x8_UNORM;
        case VK_FORMAT_ASTC_10x8_SRGB_BLOCK:
            return GERIUM_FORMAT_ASTC_10x8_SRGB;
        case VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK:
            return GERIUM_FORMAT_ASTC_10x8_SFLOAT;
        case VK_FORMAT_ASTC_10x10_UNORM_BLOCK:
            return GERIUM_FORMAT_ASTC_10x10_UNORM;
        case VK_FORMAT_ASTC_10x10_SRGB_BLOCK:
            return GERIUM_FORMAT_ASTC_10x10_SRGB;
        case VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK:
            return GERIUM_FORMAT_ASTC_10x10_SFLOAT;
        case VK_FORMAT_ASTC_12x10_UNORM_BLOCK:
            return GERIUM_FORMAT_ASTC_12x10_UNORM;
        case VK_FORMAT_ASTC_12x10_SRGB_BLOCK:
            return GERIUM_FORMAT_ASTC_12x10_SRGB;
        case VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK:
            return GERIUM_FORMAT_ASTC_12x10_SFLOAT;
        case VK_FORMAT_ASTC_12x12_UNORM_BLOCK:
            return GERIUM_FORMAT_ASTC_12x12_UNORM;
        case VK_FORMAT_ASTC_12x12_SRGB_BLOCK:
            return GERIUM_FORMAT_ASTC_12x12_SRGB;
        case VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK:
            return GERIUM_FORMAT_ASTC_12x12_SFLOAT;
        case VK_FORMAT_BC1_RGB_UNORM_BLOCK:
            return GERIUM_FORMAT_BC1_RGB_UNORM;
        case VK_FORMAT_BC1_RGB_SRGB_BLOCK:
            return GERIUM_FORMAT_BC1_RGB_SRGB;
        case VK_FORMAT_BC1_RGBA_UNORM_BLOCK:
            return GERIUM_FORMAT_BC1_RGBA_UNORM;
        case VK_FORMAT_BC1_RGBA_SRGB_BLOCK:
            return GERIUM_FORMAT_BC1_RGBA_SRGB;
        case VK_FORMAT_BC2_UNORM_BLOCK:
            return GERIUM_FORMAT_BC2_UNORM;
        case VK_FORMAT_BC2_SRGB_BLOCK:
            return GERIUM_FORMAT_BC2_SRGB;
        case VK_FORMAT_BC3_UNORM_BLOCK:
            return GERIUM_FORMAT_BC3_UNORM;
        case VK_FORMAT_BC3_SRGB_BLOCK:
            return GERIUM_FORMAT_BC3_SRGB;
        case VK_FORMAT_BC4_UNORM_BLOCK:
            return GERIUM_FORMAT_BC4_UNORM;
        case VK_FORMAT_BC4_SNORM_BLOCK:
            return GERIUM_FORMAT_BC4_SNORM;
        case VK_FORMAT_BC5_UNORM_BLOCK:
            return GERIUM_FORMAT_BC5_UNORM;
        case VK_FORMAT_BC5_SNORM_BLOCK:
            return GERIUM_FORMAT_BC5_SNORM;
        case VK_FORMAT_BC6H_UFLOAT_BLOCK:
            return GERIUM_FORMAT_BC6H_UFLOAT;
        case VK_FORMAT_BC6H_SFLOAT_BLOCK:
            return GERIUM_FORMAT_BC6H_SFLOAT;
        case VK_FORMAT_BC7_UNORM_BLOCK:
            return GERIUM_FORMAT_BC7_UNORM;
        case VK_FORMAT_BC7_SRGB_BLOCK:
            return GERIUM_FORMAT_BC7_SRGB;
        case VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK:
            return GERIUM_FORMAT_ETC2_R8G8B8_UNORM;
        case VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK:
            return GERIUM_FORMAT_ETC2_R8G8B8_SRGB;
        case VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK:
            return GERIUM_FORMAT_ETC2_R8G8B8A1_UNORM;
        case VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK:
            return GERIUM_FORMAT_ETC2_R8G8B8A1_SRGB;
        case VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK:
            return GERIUM_FORMAT_ETC2_R8G8B8A8_UNORM;
        case VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK:
            return GERIUM_FORMAT_ETC2_R8G8B8A8_SRGB;
        case VK_FORMAT_EAC_R11_UNORM_BLOCK:
            return GERIUM_FORMAT_EAC_R11_UNORM;
        case VK_FORMAT_EAC_R11_SNORM_BLOCK:
            return GERIUM_FORMAT_EAC_R11_SNORM;
        case VK_FORMAT_EAC_R11G11_UNORM_BLOCK:
            return GERIUM_FORMAT_EAC_R11G11_UNORM;
        case VK_FORMAT_EAC_R11G11_SNORM_BLOCK:
            return GERIUM_FORMAT_EAC_R11G11_SNORM;
        case VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG:
            return GERIUM_FORMAT_PVRTC1_2BPP_UNORM;
        case VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG:
            return GERIUM_FORMAT_PVRTC1_2BPP_SRGB;
        case VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG:
            return GERIUM_FORMAT_PVRTC1_4BPP_UNORM;
        case VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG:
            return GERIUM_FORMAT_PVRTC1_4BPP_SRGB;
        case VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG:
            return GERIUM_FORMAT_PVRTC2_2BPP_UNORM;
        case VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG:
            return GERIUM_FORMAT_PVRTC2_2BPP_SRGB;
        case VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG:
            return GERIUM_FORMAT_PVRTC2_4BPP_UNORM;
        case VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG:
            return GERIUM_FORMAT_PVRTC2_4BPP_SRGB;
        default:
            assert(!"unreachable code");
            return {};
    }
}

gerium_inline VkPolygonMode toVkPolygonMode(gerium_polygon_mode_t polygonMode) noexcept {
    constexpr VkPolygonMode modes[] = { VK_POLYGON_MODE_FILL, VK_POLYGON_MODE_LINE, VK_POLYGON_MODE_POINT };
    return modes[int(polygonMode)];
}

gerium_inline VkPrimitiveTopology toVkPrimitiveTopology(gerium_primitive_topology_t primitiveTopology) noexcept {
    constexpr VkPrimitiveTopology topologies[] = {
        VK_PRIMITIVE_TOPOLOGY_POINT_LIST,    VK_PRIMITIVE_TOPOLOGY_LINE_LIST,      VK_PRIMITIVE_TOPOLOGY_LINE_STRIP,
        VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP, VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN
    };
    return topologies[int(primitiveTopology)];
}

gerium_inline VkCullModeFlags toVkCullMode(gerium_cull_mode_t cullMode) noexcept {
    constexpr VkCullModeFlags modes[] = {
        VK_CULL_MODE_NONE, VK_CULL_MODE_FRONT_BIT, VK_CULL_MODE_BACK_BIT, VK_CULL_MODE_FRONT_AND_BACK
    };
    return modes[int(cullMode)];
}

gerium_inline VkCompareOp toVkCompareOp(gerium_compare_op_t compareOp) noexcept {
    constexpr VkCompareOp compares[] = { VK_COMPARE_OP_NEVER,   VK_COMPARE_OP_ALWAYS,
                                         VK_COMPARE_OP_LESS,    VK_COMPARE_OP_LESS_OR_EQUAL,
                                         VK_COMPARE_OP_GREATER, VK_COMPARE_OP_GREATER_OR_EQUAL,
                                         VK_COMPARE_OP_EQUAL,   VK_COMPARE_OP_NOT_EQUAL };
    return compares[int(compareOp)];
}

gerium_inline VkStencilOp toVkStencilOp(gerium_stencil_op_t stencilOp) noexcept {
    constexpr VkStencilOp stencils[] = { VK_STENCIL_OP_KEEP,
                                         VK_STENCIL_OP_ZERO,
                                         VK_STENCIL_OP_REPLACE,
                                         VK_STENCIL_OP_INVERT,
                                         VK_STENCIL_OP_INCREMENT_AND_CLAMP,
                                         VK_STENCIL_OP_DECREMENT_AND_CLAMP,
                                         VK_STENCIL_OP_INCREMENT_AND_WRAP,
                                         VK_STENCIL_OP_DECREMENT_AND_WRAP };
    return stencils[int(stencilOp)];
}

gerium_inline VkLogicOp toVkLogicOp(gerium_logic_op_t logicOp) noexcept {
    constexpr VkLogicOp logics[] = { VK_LOGIC_OP_CLEAR,       VK_LOGIC_OP_SET,           VK_LOGIC_OP_NO_OP,
                                     VK_LOGIC_OP_COPY,        VK_LOGIC_OP_COPY_INVERTED, VK_LOGIC_OP_AND,
                                     VK_LOGIC_OP_AND_REVERSE, VK_LOGIC_OP_AND_INVERTED,  VK_LOGIC_OP_NAND,
                                     VK_LOGIC_OP_OR,          VK_LOGIC_OP_OR_REVERSE,    VK_LOGIC_OP_OR_INVERTED,
                                     VK_LOGIC_OP_NOR,         VK_LOGIC_OP_XOR,           VK_LOGIC_OP_EQUIVALENT,
                                     VK_LOGIC_OP_INVERT };
    return logics[int(logicOp)];
}

gerium_inline VkBlendOp toVkBlendOp(gerium_blend_op_t blendOp) noexcept {
    constexpr VkBlendOp blends[] = {
        VK_BLEND_OP_ADD, VK_BLEND_OP_SUBTRACT, VK_BLEND_OP_REVERSE_SUBTRACT, VK_BLEND_OP_MIN, VK_BLEND_OP_MAX
    };
    return blends[int(blendOp)];
}

gerium_inline VkBlendFactor toVkBlendFactor(gerium_blend_factor_t blendFactor) noexcept {
    constexpr VkBlendFactor factors[] = { VK_BLEND_FACTOR_ZERO,
                                          VK_BLEND_FACTOR_ONE,
                                          VK_BLEND_FACTOR_SRC_COLOR,
                                          VK_BLEND_FACTOR_SRC_ALPHA,
                                          VK_BLEND_FACTOR_SRC_ALPHA_SATURATE,
                                          VK_BLEND_FACTOR_DST_COLOR,
                                          VK_BLEND_FACTOR_DST_ALPHA,
                                          VK_BLEND_FACTOR_CONSTANT_COLOR,
                                          VK_BLEND_FACTOR_CONSTANT_ALPHA,
                                          VK_BLEND_FACTOR_SRC1_COLOR,
                                          VK_BLEND_FACTOR_SRC1_ALPHA,
                                          VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR,
                                          VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
                                          VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR,
                                          VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA,
                                          VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR,
                                          VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA,
                                          VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR,
                                          VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA };
    return factors[int(blendFactor)];
}

gerium_inline VkColorComponentFlags toVkColorComponent(gerium_color_component_flags_t colorComponentFlags) noexcept {
    return (VkColorComponentFlags) colorComponentFlags;
}

gerium_inline VkFrontFace toVkFrontFace(gerium_front_face_t frontFace) noexcept {
    constexpr VkFrontFace faces[] = { VK_FRONT_FACE_COUNTER_CLOCKWISE, VK_FRONT_FACE_CLOCKWISE };
    return faces[int(frontFace)];
}

gerium_inline VkBufferUsageFlags toVkBufferUsageFlags(gerium_buffer_usage_flags_t flags) noexcept {
    VkBufferUsageFlags result{};

    if ((flags & GERIUM_BUFFER_USAGE_VERTEX_BIT) == GERIUM_BUFFER_USAGE_VERTEX_BIT) {
        result |= VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
    }

    if ((flags & GERIUM_BUFFER_USAGE_INDEX_BIT) == GERIUM_BUFFER_USAGE_INDEX_BIT) {
        result |= VK_BUFFER_USAGE_INDEX_BUFFER_BIT;
    }

    if ((flags & GERIUM_BUFFER_USAGE_UNIFORM_BIT) == GERIUM_BUFFER_USAGE_UNIFORM_BIT) {
        result |= VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT;
    }

    if ((flags & GERIUM_BUFFER_USAGE_STORAGE_BIT) == GERIUM_BUFFER_USAGE_STORAGE_BIT) {
        result |= VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
    }

    if ((flags & GERIUM_BUFFER_USAGE_INDIRECT_BIT) == GERIUM_BUFFER_USAGE_INDIRECT_BIT) {
        result |= VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT;
    }

    return result;
}

gerium_inline VkImageType toVkImageType(gerium_texture_type_t type) noexcept {
    switch (type) {
        case GERIUM_TEXTURE_TYPE_1D:
            return VK_IMAGE_TYPE_1D;
        case GERIUM_TEXTURE_TYPE_2D:
        case GERIUM_TEXTURE_TYPE_CUBE:
            return VK_IMAGE_TYPE_2D;
        case GERIUM_TEXTURE_TYPE_3D:
            return VK_IMAGE_TYPE_3D;
        default:
            assert(!"unreachable code");
            return {};
    }
}

gerium_inline VkFilter toVkFilter(gerium_filter_t filter) noexcept {
    return (VkFilter) filter;
}

gerium_inline VkSamplerMipmapMode toVkSamplerMipmapMode(gerium_filter_t filter) noexcept {
    return (VkSamplerMipmapMode) filter;
}

gerium_inline VkSamplerAddressMode toVkSamplerAddressMode(gerium_address_mode_t mode) noexcept {
    return (VkSamplerAddressMode) mode;
}

gerium_inline VkSamplerReductionMode toVkSamplerReductionMode(gerium_reduction_mode_t mode) noexcept {
    return (VkSamplerReductionMode) mode;
}

gerium_inline VkImageViewType toVkImageViewType(gerium_texture_type_t type, bool arrayed) noexcept {
    constexpr VkImageViewType types[] = {
        VK_IMAGE_VIEW_TYPE_1D, VK_IMAGE_VIEW_TYPE_2D, VK_IMAGE_VIEW_TYPE_3D, VK_IMAGE_VIEW_TYPE_CUBE
    };

    constexpr VkImageViewType arrayTypes[] = {
        VK_IMAGE_VIEW_TYPE_1D_ARRAY, VK_IMAGE_VIEW_TYPE_2D_ARRAY, {}, VK_IMAGE_VIEW_TYPE_CUBE_ARRAY
    };

    return !arrayed ? types[(int) type] : arrayTypes[(int) type];
}

gerium_inline VkShaderStageFlagBits toVkShaderStage(gerium_shader_type_t type) noexcept {
    switch (type) {
        case GERIUM_SHADER_TYPE_VERTEX:
            return VK_SHADER_STAGE_VERTEX_BIT;
        case GERIUM_SHADER_TYPE_FRAGMENT:
            return VK_SHADER_STAGE_FRAGMENT_BIT;
        case GERIUM_SHADER_TYPE_COMPUTE:
            return VK_SHADER_STAGE_COMPUTE_BIT;
        case GERIUM_SHADER_TYPE_TASK:
            return VK_SHADER_STAGE_TASK_BIT_EXT;
        case GERIUM_SHADER_TYPE_MESH:
            return VK_SHADER_STAGE_MESH_BIT_EXT;
        default:
            assert(!"TODO");
            return {};
    }
}

gerium_inline gerium_shader_type_t toGerumShaderType(VkShaderStageFlagBits type) noexcept {
    switch (type) {
        case VK_SHADER_STAGE_VERTEX_BIT:
            return GERIUM_SHADER_TYPE_VERTEX;
        case VK_SHADER_STAGE_FRAGMENT_BIT:
            return GERIUM_SHADER_TYPE_FRAGMENT;
        case VK_SHADER_STAGE_COMPUTE_BIT:
            return GERIUM_SHADER_TYPE_COMPUTE;
        case VK_SHADER_STAGE_TASK_BIT_EXT:
            return GERIUM_SHADER_TYPE_TASK;
        case VK_SHADER_STAGE_MESH_BIT_EXT:
            return GERIUM_SHADER_TYPE_MESH;
        default:
            assert(!"TODO");
            return {};
    }
}

gerium_inline VkImageAspectFlags toVkImageAspect(VkFormat format) noexcept {
    VkImageAspectFlags aspect{};
    if (hasDepthOrStencil(format)) {
        if (hasDepth(format)) {
            aspect = VK_IMAGE_ASPECT_DEPTH_BIT;
        }
        if (hasStencil(format)) {
            aspect |= VK_IMAGE_ASPECT_STENCIL_BIT;
        }
    } else {
        aspect = VK_IMAGE_ASPECT_COLOR_BIT;
    }
    return aspect;
}

gerium_inline VkIndexType toVkIndexType(gerium_index_type_t type) noexcept {
    return (VkIndexType) type;
}

gerium_inline VkAccessFlags toVkAccessFlags(ResourceState state) noexcept {
    VkAccessFlags ret = 0;
    if ((state & ResourceState::CopySource) == ResourceState::CopySource) {
        ret |= VK_ACCESS_TRANSFER_READ_BIT;
    }
    if ((state & ResourceState::CopyDest) == ResourceState::CopyDest) {
        ret |= VK_ACCESS_TRANSFER_WRITE_BIT;
    }
    if ((state & ResourceState::VertexAndConstantBuffer) == ResourceState::VertexAndConstantBuffer) {
        ret |= VK_ACCESS_UNIFORM_READ_BIT | VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT;
    }
    if ((state & ResourceState::IndexBuffer) == ResourceState::IndexBuffer) {
        ret |= VK_ACCESS_INDEX_READ_BIT;
    }
    if ((state & ResourceState::UnorderedAccess) == ResourceState::UnorderedAccess) {
        ret |= VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT;
    }
    if ((state & ResourceState::IndirectArgument) == ResourceState::IndirectArgument) {
        ret |= VK_ACCESS_INDIRECT_COMMAND_READ_BIT;
    }
    if ((state & ResourceState::RenderTarget) == ResourceState::RenderTarget) {
        ret |= VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    }
    if ((state & ResourceState::DepthWrite) == ResourceState::DepthWrite) {
        ret |= VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT;
    }
    if ((state & ResourceState::DepthRead) == ResourceState::DepthRead) {
        ret |= VK_ACCESS_SHADER_READ_BIT;
    }
    if ((state & ResourceState::ShaderResource) == ResourceState::ShaderResource) {
        ret |= VK_ACCESS_SHADER_READ_BIT;
    }
    if ((state & ResourceState::Present) == ResourceState::Present) {
        ret |= VK_ACCESS_MEMORY_READ_BIT;
    }
    return ret;
}

gerium_inline VkImageLayout toVkImageLayout(ResourceState usage) noexcept {
    if ((usage & ResourceState::CopySource) == ResourceState::CopySource) {
        return VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
    }

    if ((usage & ResourceState::CopyDest) == ResourceState::CopyDest) {
        return VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    }

    if ((usage & ResourceState::RenderTarget) == ResourceState::RenderTarget) {
        return VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    }

    if ((usage & ResourceState::DepthWrite) == ResourceState::DepthWrite) {
        return VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;
    }

    if ((usage & ResourceState::DepthRead) == ResourceState::DepthRead) {
        return VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL;
    }

    if ((usage & ResourceState::UnorderedAccess) == ResourceState::UnorderedAccess) {
        return VK_IMAGE_LAYOUT_GENERAL;
    }

    if ((usage & ResourceState::ShaderResource) == ResourceState::ShaderResource) {
        return VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
    }

    if ((usage & ResourceState::Present) == ResourceState::Present) {
        return VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;
    }

    if (usage == ResourceState::Common) {
        return VK_IMAGE_LAYOUT_GENERAL;
    }

    return VK_IMAGE_LAYOUT_UNDEFINED;
}

gerium_inline VkPipelineStageFlags utilDeterminePipelineStageFlags(VkAccessFlags accessFlags,
                                                                   QueueType queueType) noexcept {
    VkPipelineStageFlags flags = 0;

    switch (queueType) {
        case QueueType::Graphics: {
            if ((accessFlags & (VK_ACCESS_INDEX_READ_BIT | VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT)) != 0) {
                flags |= VK_PIPELINE_STAGE_VERTEX_INPUT_BIT;
            }

            if ((accessFlags & (VK_ACCESS_UNIFORM_READ_BIT | VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT)) !=
                0) {
                flags |= VK_PIPELINE_STAGE_VERTEX_SHADER_BIT;
                flags |= VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
                flags |= VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT;
            }

            if ((accessFlags & VK_ACCESS_INPUT_ATTACHMENT_READ_BIT) != 0) {
                flags |= VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
            }

            if ((accessFlags & (VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT)) != 0) {
                flags |= VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
            }

            if ((accessFlags &
                 (VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT)) != 0) {
                flags |= VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT | VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT;
            }

            break;
        }
        case QueueType::Compute: {
            if ((accessFlags & (VK_ACCESS_INDEX_READ_BIT | VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT)) != 0 ||
                (accessFlags & VK_ACCESS_INPUT_ATTACHMENT_READ_BIT) != 0 ||
                (accessFlags & (VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT)) != 0 ||
                (accessFlags &
                 (VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT)) != 0) {
                return VK_PIPELINE_STAGE_ALL_COMMANDS_BIT;
            }

            if ((accessFlags & (VK_ACCESS_UNIFORM_READ_BIT | VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT)) !=
                0) {
                flags |= VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT;
            }

            break;
        }
        case QueueType::CopyTransfer:
            return VK_PIPELINE_STAGE_ALL_COMMANDS_BIT;
        default:
            break;
    }

    if ((accessFlags & VK_ACCESS_INDIRECT_COMMAND_READ_BIT) != 0) {
        flags |= VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT;
    }

    if ((accessFlags & (VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT)) != 0) {
        flags |= VK_PIPELINE_STAGE_TRANSFER_BIT;
    }

    if ((accessFlags & (VK_ACCESS_HOST_READ_BIT | VK_ACCESS_HOST_WRITE_BIT)) != 0) {
        flags |= VK_PIPELINE_STAGE_HOST_BIT;
    }

    if (flags == 0) {
        flags = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
    }

    return flags;
}

} // namespace gerium::vulkan

#endif
