name: base
pipelines:
  - render pass: skydome_gen_pass
    shaders:
      - type: GERIUM_SHADER_TYPE_COMPUTE
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/skydome_gen.comp.glsl

  - render pass: skydome_prefiltered_pass
    shaders:
      - type: GERIUM_SHADER_TYPE_COMPUTE
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/skydome_prefiltered.comp.glsl

  - render pass: skydome_pass
    depth stencil:
      depth test enable: true
      depth compare op: GERIUM_COMPARE_OP_GREATER_OR_EQUAL
    shaders:
      - type: GERIUM_SHADER_TYPE_VERTEX
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/skydome.vert.glsl
      - type: GERIUM_SHADER_TYPE_FRAGMENT
        lang: GERIUM_SHADER_LANGUAGE_GLSL
        name: shaders/skydome.frag.glsl
